language: node_js
node_js:
  - "9"
before_script: "yarn global add eslint jest mocha"
cache:
  directories:
    - node_modules
    - client/node_modules
env:
  global:
    - secure: lcmZh2HB9EmVfRL7YbyQgO3bOq7KNRsJfR8gsEbJoG4vewrzYS4Y5quWAqPabvkfCKtyhTSbiTC2+f8GIU7uTNClC5ZzG2Hlhvj3muPePxkMZf2/w9Fjo7Izxwha5nP5dgJnWzJ0I964MFKXBrdi/J+aOj3pRWsseo6uIxGgkiqxt7UZzTHruMbgiXfGy9LePrh+oHazGG6RP2Ap54cM/JShvIMbbqjHQpx5t5YZHdP2gV+ABRHOK+WxKft1EfhTufsf33xGetpNnWVX3PxWXPFzhwhh+lOkNM8R+/At4nmI84axzGUn1rWoZxpqDO5GoTTeJjMz3ECEP4y5j+gXU6Dme16L2NI7Y8lcuk+5Y/gb5OaTkQQw1a/97rvUyD8D+o2Npib+36XYMJp3vek5Sz5JP0JV3TETh5WBR1g+VslYCF0rV8trODDWE5EdVL0HDE40UyUqzNmVxhFODv2eoHx9dqmNi/Qwpb3Y81+EPt4IvLZstYTDLHFSN1HIWpBb0Y6kiM2KeanDEf0tvsZ+2VfpsW90x73r1YOYOhrCiqbWF8rnUvITuSnSwDr52kIseF6xuBErH1TQeazE+qqBDFVPQ2sqfbJbzFIyIB2cEvDPzu91QOLFaMVYEw7rWZydOZ3Fb3UKm9p9bGRBALNzdlzDmRCTLI1ncF3ccoocIOI=
